<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\License;
use App\Models\Category;
use App\Models\Brand;
use App\Models\Setting;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // Software
            [
                'name' => 'Windows 11 Pro',
                'slug' => 'windows-11-pro',
                'type' => 'license',
                'category' => 'windows',
                'brand' => 'microsoft',
                'description' => 'Licencia original de Windows 11 Professional. Activación en línea, uso indefinido.',
                'price' => 29.99,
                'compare_price' => 199.99,
                'discount' => 85,
                'stock' => 50,
                'is_featured' => true,
                'platform' => 'PC',
                'region' => 'Global',
                'activation_method' => 'Clave de producto',
                'delivery_time' => 'Instantánea',
                'warranty_days' => 30,
            ],
            [
                'name' => 'Windows 10 Home',
                'slug' => 'windows-10-home',
                'type' => 'license',
                'category' => 'windows',
                'brand' => 'microsoft',
                'description' => 'Licencia original de Windows 10 Home. Compatible con todas las versiones recientes.',
                'price' => 19.99,
                'compare_price' => 139.99,
                'discount' => 86,
                'stock' => 75,
                'is_featured' => false,
                'platform' => 'PC',
                'region' => 'Global',
                'activation_method' => 'Clave de producto',
                'delivery_time' => 'Instantánea',
                'warranty_days' => 30,
            ],
            [
                'name' => 'Microsoft Office 2021 Professional Plus',
                'slug' => 'office-2021-professional-plus',
                'type' => 'license',
                'category' => 'office',
                'brand' => 'microsoft',
                'description' => 'Incluye Word, Excel, PowerPoint, Outlook, Access y Publisher. Licencia perpetua.',
                'price' => 49.99,
                'compare_price' => 449.99,
                'discount' => 89,
                'stock' => 30,
                'is_featured' => true,
                'platform' => 'PC',
                'region' => 'Global',
                'activation_method' => 'Clave de producto',
                'delivery_time' => 'Instantánea',
                'warranty_days' => 30,
            ],
            [
                'name' => 'Microsoft 365 Personal (1 Año)',
                'slug' => 'microsoft-365-personal',
                'type' => 'subscription',
                'category' => 'office',
                'brand' => 'microsoft',
                'description' => 'Suscripción de 1 año con Word, Excel, PowerPoint, 1TB OneDrive y 60min Skype.',
                'price' => 34.99,
                'compare_price' => 69.99,
                'discount' => 50,
                'stock' => 100,
                'is_featured' => true,
                'platform' => 'Multiplataforma',
                'region' => 'Global',
                'activation_method' => 'Cuenta Microsoft',
                'delivery_time' => 'Instantánea',
                'warranty_days' => 30,
            ],
            // Antivirus
            [
                'name' => 'Norton 360 Deluxe (1 Año, 5 Dispositivos)',
                'slug' => 'norton-360-deluxe',
                'type' => 'license',
                'category' => 'antivirus',
                'brand' => 'norton',
                'description' => 'Protección avanzada para hasta 5 dispositivos. Incluye VPN y monitor de dark web.',
                'price' => 14.99,
                'compare_price' => 49.99,
                'discount' => 70,
                'stock' => 200,
                'is_featured' => true,
                'platform' => 'Multiplataforma',
                'region' => 'Global',
                'activation_method' => 'Cuenta Norton',
                'delivery_time' => 'Instantánea',
                'warranty_days' => 30,
            ],
            [
                'name' => 'Kaspersky Total Security (1 Año, 3 Dispositivos)',
                'slug' => 'kaspersky-total-security',
                'type' => 'license',
                'category' => 'antivirus',
                'brand' => 'kaspersky',
                'description' => 'Protección completa contra virus, ransomware y más. Incluye gestor de contraseñas.',
                'price' => 12.99,
                'compare_price' => 39.99,
                'discount' => 68,
                'stock' => 150,
                'is_featured' => false,
                'platform' => 'Multiplataforma',
                'region' => 'Global',
                'activation_method' => 'Cuenta Kaspersky',
                'delivery_time' => 'Instantánea',
                'warranty_days' => 30,
            ],
            // Juegos - Steam
            [
                'name' => 'Steam Wallet Card $50 USD',
                'slug' => 'steam-wallet-50',
                'type' => 'giftcard',
                'category' => 'gift-cards',
                'brand' => 'steam-brand',
                'description' => 'Tarjeta de regalo Steam de $50 USD. Recarga tu billetera Steam y compra juegos.',
                'price' => 47.99,
                'compare_price' => 50.00,
                'discount' => 4,
                'stock' => 100,
                'is_featured' => true,
                'platform' => 'Steam',
                'region' => 'Global',
                'activation_method' => 'Código Steam',
                'delivery_time' => 'Instantánea',
                'warranty_days' => 7,
            ],
            [
                'name' => 'Steam Wallet Card $20 USD',
                'slug' => 'steam-wallet-20',
                'type' => 'giftcard',
                'category' => 'gift-cards',
                'brand' => 'steam-brand',
                'description' => 'Tarjeta de regalo Steam de $20 USD.',
                'price' => 19.49,
                'compare_price' => 20.00,
                'discount' => 3,
                'stock' => 200,
                'is_featured' => false,
                'platform' => 'Steam',
                'region' => 'Global',
                'activation_method' => 'Código Steam',
                'delivery_time' => 'Instantánea',
                'warranty_days' => 7,
            ],
            // Xbox
            [
                'name' => 'Xbox Game Pass Ultimate (3 Meses)',
                'slug' => 'xbox-game-pass-ultimate-3m',
                'type' => 'subscription',
                'category' => 'xbox',
                'brand' => 'xbox-brand',
                'description' => 'Acceso a cientos de juegos en consola, PC y nube. Incluye Xbox Live Gold.',
                'price' => 29.99,
                'compare_price' => 44.99,
                'discount' => 33,
                'stock' => 80,
                'is_featured' => true,
                'platform' => 'Xbox / PC',
                'region' => 'Global',
                'activation_method' => 'Cuenta Microsoft',
                'delivery_time' => 'Instantánea',
                'warranty_days' => 14,
            ],
            // PlayStation
            [
                'name' => 'PlayStation Plus Essential (3 Meses)',
                'slug' => 'ps-plus-essential-3m',
                'type' => 'subscription',
                'category' => 'playstation',
                'brand' => 'playstation-brand',
                'description' => 'Juegos gratuitos mensuales, multijugador online y 100GB de almacenamiento en la nube.',
                'price' => 17.99,
                'compare_price' => 24.99,
                'discount' => 28,
                'stock' => 60,
                'is_featured' => true,
                'platform' => 'PlayStation',
                'region' => 'Global',
                'activation_method' => 'Cuenta PSN',
                'delivery_time' => 'Instantánea',
                'warranty_days' => 14,
            ],
            // Streaming
            [
                'name' => 'Netflix Premium (1 Mes)',
                'slug' => 'netflix-premium-1m',
                'type' => 'subscription',
                'category' => 'streaming',
                'brand' => 'netflix',
                'description' => 'Cuenta Premium de Netflix con 4K UHD y 4 pantallas simultáneas. 1 mes de duración.',
                'price' => 8.99,
                'compare_price' => 22.99,
                'discount' => 61,
                'stock' => 50,
                'is_featured' => true,
                'platform' => 'Multiplataforma',
                'region' => 'Global',
                'activation_method' => 'Cuenta Netflix',
                'delivery_time' => 'Instantánea',
                'warranty_days' => 7,
            ],
            [
                'name' => 'Spotify Premium (3 Meses)',
                'slug' => 'spotify-premium-3m',
                'type' => 'subscription',
                'category' => 'streaming',
                'brand' => 'spotify',
                'description' => 'Cuenta Premium de Spotify sin anuncios y con descarga offline. 3 meses.',
                'price' => 9.99,
                'compare_price' => 16.99,
                'discount' => 41,
                'stock' => 120,
                'is_featured' => false,
                'platform' => 'Multiplataforma',
                'region' => 'Global',
                'activation_method' => 'Cuenta Spotify',
                'delivery_time' => 'Instantánea',
                'warranty_days' => 14,
            ],
            // Adobe
            [
                'name' => 'Adobe Photoshop CC (1 Año)',
                'slug' => 'adobe-photoshop-cc',
                'type' => 'license',
                'category' => 'software',
                'brand' => 'adobe',
                'description' => 'Licencia de Adobe Photoshop CC por 1 año. Incluye todas las actualizaciones.',
                'price' => 89.99,
                'compare_price' => 264.00,
                'discount' => 66,
                'stock' => 25,
                'is_featured' => true,
                'platform' => 'PC / Mac',
                'region' => 'Global',
                'activation_method' => 'Cuenta Adobe',
                'delivery_time' => 'Instantánea',
                'warranty_days' => 30,
            ],
            [
                'name' => 'Adobe Creative Cloud (1 Año)',
                'slug' => 'adobe-creative-cloud',
                'type' => 'license',
                'category' => 'software',
                'brand' => 'adobe',
                'description' => 'Acceso completo a todas las aplicaciones de Adobe: Photoshop, Illustrator, Premiere, After Effects y más.',
                'price' => 149.99,
                'compare_price' => 599.99,
                'discount' => 75,
                'stock' => 15,
                'is_featured' => true,
                'platform' => 'PC / Mac',
                'region' => 'Global',
                'activation_method' => 'Cuenta Adobe',
                'delivery_time' => 'Instantánea',
                'warranty_days' => 30,
            ],
            // Bitdefender
            [
                'name' => 'Bitdefender Total Security (1 Año, 5 Dispositivos)',
                'slug' => 'bitdefender-total-security',
                'type' => 'license',
                'category' => 'antivirus',
                'brand' => 'bitdefender',
                'description' => 'Protección de máxima velocidad contra todas las amenazas. Incluye VPN y anti-ransomware.',
                'price' => 15.99,
                'compare_price' => 44.99,
                'discount' => 64,
                'stock' => 90,
                'is_featured' => false,
                'platform' => 'Multiplataforma',
                'region' => 'Global',
                'activation_method' => 'Cuenta Bitdefender',
                'delivery_time' => 'Instantánea',
                'warranty_days' => 30,
            ],
        ];

        foreach ($products as $productData) {
            $category = Category::where('slug', $productData['category'])->first();
            $brand = Brand::where('slug', $productData['brand'])->first();

            $product = Product::create([
                'name' => $productData['name'],
                'slug' => $productData['slug'],
                'type' => $productData['type'],
                'category_id' => $category->id,
                'brand_id' => $brand?->id,
                'description' => $productData['description'],
                'price' => $productData['price'],
                'compare_price' => $productData['compare_price'],
                'discount' => $productData['discount'],
                'stock' => $productData['stock'],
                'is_featured' => $productData['is_featured'],
                'is_active' => true,
                'platform' => $productData['platform'],
                'region' => $productData['region'],
                'activation_method' => $productData['activation_method'],
                'delivery_time' => $productData['delivery_time'],
                'warranty_days' => $productData['warranty_days'],
            ]);

            // Create licenses for each product
            $licenseCount = min($productData['stock'], 20);
            for ($i = 0; $i < $licenseCount; $i++) {
                License::create([
                    'product_id' => $product->id,
                    'key' => strtoupper(bin2hex(random_bytes(8))),
                    'status' => 'available',
                ]);
            }
        }

        // Create settings
        $settings = [
            ['key' => 'site_name', 'value' => 'TodoKeys', 'group' => 'general'],
            ['key' => 'site_description', 'value' => 'Tu tienda de confianza para licencias digitales', 'group' => 'general'],
            ['key' => 'site_currency', 'value' => 'USD', 'group' => 'general'],
            ['key' => 'site_email', 'value' => 'soporte@todokeys.com', 'group' => 'general'],
            ['key' => 'tax_rate', 'value' => '0', 'group' => 'general'],
            ['key' => 'free_shipping_min', 'value' => '0', 'group' => 'general'],
        ];

        foreach ($settings as $setting) {
            Setting::create($setting);
        }
    }
}
